version: '3.8'

services:
  fastapi:
    build:
      context: ./fast-api
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
