name: Docker Compose CI

on:
  release:
    types: [published]
  push:
    branches:
      - main  # Specify the branches you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for services to be ready
      run: |
        until curl -s http://localhost:80 > /dev/null; do
          echo "Waiting for Nginx to be ready..."
          sleep 5
        done
        until curl -s http://localhost:10000 > /dev/null; do
          echo "Waiting for FastAPI to be ready..."
          sleep 5
        done

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set tag for release
      if: github.event_name == 'release'
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set tag for push
      if: github.event_name == 'push'
      run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml push
      env:
        TAG: ${{ env.TAG }}
