name: Docker Compose CI

on:
  release:
    types: [published]
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

    - name: Run Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for services to be ready
      run: |
        until curl -s http://localhost:80 > /dev/null; do
          echo "Waiting for Nginx to be ready..."
          sleep 5
        done
        until curl -s http://localhost:10000 > /dev/null; do
          echo "Waiting for FastAPI to be ready..."
          sleep 5
        done

    - name: Test Nginx connection
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80)
        if [ "$response" -ne 200 ]; then
          echo "Nginx is not responding with HTTP 200"
          exit 1
        fi

    - name: Test FastAPI connection
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:10000)
        if [ "$response" -ne 200 ]; then
          echo "FastAPI is not responding with HTTP 200"
          exit 1
        fi

    - name: Run tests
      run: |
        docker-compose -f docker-compose.yml exec fastapi_app pytest

    - name: Shutdown Docker Compose
      run: docker-compose -f docker-compose.yml down
