name: Run Pytest

on:
  push:
    branches:
      - main  # You can specify other branches or events as needed
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fast-api/requirements.txt
        pip install pytest httpx

    - name: Run tests
      run: |
        cd fast-api
        pytest
