name: Python tests

on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r fast-api/requirements.txt
        pip install pytest httpx

    - name: Set environment variables
      env:
        OPENCVE_USERNAME: ${{ secrets.OPENCVE_USERNAME }}
        OPENCVE_PASSWORD: ${{ secrets.OPENCVE_PASSWORD }}
      run: |
        echo "USERNAME=$OPENCVE_USERNAME" >> $GITHUB_ENV
        echo "PASSWORD=$OPENCVE_PASSWORD" >> $GITHUB_ENV

    - name: Run tests
      run: |
        cd fast-api
        pytest
